sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t umakanuri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true umakanuri/react-test npm run test -- --coverage

after_success:
  - docker build -t ukanuri/multi-client ./client
  - docker build -t ukanuri/multi-nginx ./nginx
  - docker build -t ukanuri/multi-server ./server
  - docker build -t ukanuri/multi-worker ./worker
  #Lon in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #The these images and push them to docker hub
  - docker push ukanuri/multi-client
  - docker push ukanuri/multi-nginx
  - docker push ukanuri/multi-server
  - docker push ukanuri/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-088745045272
  bucket_path: docket-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY